### ISSUE TITLE
Run time error when using an AoT build

### ISSUE THREAD

**Issue by MrTimms** [MarkPieszak/angular-application-insights#10]
I'm using Angular 4.0.1, Angular-CLI 1.0.0, and @markpieszak/ng-application-insights 1.0.0

Everything works perfectly when I run a debug build. However, once I add the --aot flag I receive 2 compile time warnings and a run time error. 

Please let me know if you need more information.

Compile time warnings:

    WARNING in ./~/@markpieszak/ng-application-insights/~/@angular/router/src/private_import_core.js 9:40-41 "export '__core_private__' (imported as 'r') was not found in '@angular/core'

    WARNING in ./~/@markpieszak/ng-application-insights/~/@angular/router/src/private_import_core.js 10:43-44 "export '__core_private__' (imported as 'r') was not found in '@angular/core'

Run time error:

    Uncaught TypeError: Cannot read property 'isPromise' of undefined
        at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:66581:97)
        at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
        at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:41327:79)
        at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
        at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:55237:76)
        at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
        at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:65278:80)
        at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
        at Object.RouterOutletMap.registerOutlet.outlet._outlets.(anonymous function) (http://localhost:4200/vendor.bundle.js:67022:76)
        at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
        at Object.389 (http://localhost:4200/main.bundle.js:3675:135)
        at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
        at Object.351 (http://localhost:4200/main.bundle.js:390:88)
        at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
        at Object.894 (http://localhost:4200/main.bundle.js:10298:18)

Here is the relevant part of my app.module file:

    import { ApplicationInsightsModule, AppInsightsService } from '@markpieszak/ng-application-insights';
    @NgModule({
      imports: [
        ...
        ApplicationInsightsModule.forRoot({ instrumentationKey: 'My-Key' })
      ],
       ...

      providers: [
         ...
        AppInsightsService,
       ...
      ]

Here is the relevant part of my component:

    import { AppInsightsService } from '@markpieszak/ng-application-insights';
    ...

    constructor(
       ...
       private appInsightsService: AppInsightsService
    ) {}
    
    ...
    doSomething() {
         this.appInsightsService.trackEvent('WelcomePage')

**Comment by MarkPieszak** [comment]
This may be due to the fact that we're using the older 2.x router and you're on 4.
Might have to upgrade it within the library here!

**Comment by viperguynaz** [comment]
@MarkPieszak I was going to recommend freezing minimum capabilitywe've implemented @ 1.0.0 and then bump to 4.0.0 to align with NG4 - I have an implementation done, should be able to get  PR up tonight.

**Comment by MarkPieszak** [comment]
ahh good idea, don't think we need to align with Core though 😜 
Maybe just 2.0?

**Comment by MarkPieszak** [comment]
@MrTimms can you try 2.0 thanks to @viperguynaz

**Comment by MrTimms** [comment]
@MarkPieszak @viperguynaz Everything is working. Thanks!

**Comment by DnyaneshwarShivbhakta** [comment]
@MarkPieszak :- I am also unable to find __core_private__  and __platform_browser_private__ member after migrating from angular 2 to angular 6.Could you please help me to resolve this issue.
