### ISSUE TITLE
Cannot read property 'isPromise' of undefined

### ISSUE THREAD

**Issue by sat80890** [MarkPieszak/angular-application-insights#31]
This is looks like similar to [https://github.com/MarkPieszak/angular-application-insights/issues/10](https://github.com/MarkPieszak/angular-application-insights/issues/10)
But, i have Angular 4.2.1 with 
"dependencies": {
                     "attherate markpieszak/ng-application-insights": "^2.4.2",
}

Runtime Error
Cannot read property 'isPromise' of undefined

Stack:
TypeError: Cannot read property 'isPromise' of undefined
    at Object.<anonymous> (http://localhost:8100/build/main.js:144370:98)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:34023:79)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:52567:76)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:142966:80)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:51037:76)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)

Ionic Framework: 3.3.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.2
Angular Compiler CLI: 4.1.2
Node: 6.11.4
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by sat80890** [comment]
do we have any update ? @MarkPieszak @KamilSzostak @Dmitry-Matveev @johnkattenhorn

**Comment by MarkPieszak** [comment]
Hey @sat80890 Apologies on the delay, github notifications are a mess!
Did you ever figure this one out? 
It sounds like you might need to dump `node_modules` and reinstall everything, make sure it's using the correct versions in node_modules manually afterwards, maybe something is installing older versions for some reason.

Let me know!

**Comment by navarrofracisco** [comment]
@MarkPieszak  Hi there, facing the same problem. I removed the node_modules and ran the following commands and I still continue to see the same problem.
npm cache clean
npm install

Version:
"dependencies": {
    "@angular/router": "^4.1.3",
    "@markpieszak/ng-application-insights": "^1.0.0",
}

![image](https://user-images.githubusercontent.com/8353831/33904618-f6dfac42-df30-11e7-917e-2d72fdb3cd60.png)

**Comment by MarkPieszak** [comment]
So you need to use `^2.0.0` at least, that `^` will only stay within that current semantic versioning of ^1.0.0 you have in your package.json, that should fix it!
@sat80890 If you can upgrade to 2.x that'd fix your issue as well.

Let me know! Closing out for now.
